#!/usr/bin/expect -f

set timeout 30
set host "54.37.158.9"
set user "debian"
set password "Kronito2025."
set command [lindex $argv 0]

spawn ssh -o StrictHostKeyChecking=no ${user}@${host} "$command"
expect {
    "password:" {
        send "${password}\r"
        exp_continue
    }
    "Password:" {
        send "${password}\r"
        exp_continue
    }
    "$ " {
        interact
    }
    eof
}

